[package]
name = "polaris_marketplace"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "1.16.0"
spl-token = { version="3.5.0", features = [ "no-entrypoint" ] }
borsh = "0.10.3"
